apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testpod
  name: testpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testpod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testpod
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-helloworld: "internal/database/config"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-inject-template-helloworld: |-
          {{- with secret "internal/database/config" -}}
            #!/bin/bash
            echo  'export db_password="{{ .Data.data.password}}"' >> ~/.bashrc 
            echo  'export db_username="{{ .Data.data.username}}"' >> ~/.bashrc 
          {{- end }}
    spec:
      serviceAccountName: myapp
      containers:
      - image: nginx
        name: nginx
        command: ["/bin/bash","-c"]
        # args: ["/bin/bash", "-c", "./vault/secrets/helloworld && source ~/.bashrc  && nginx-debug -g 'daemon off;'"]
        args:
          - |
            chmod +x /vault/secrets/helloworld
            sh -x /vault/secrets/helloworld
            source ~/.bashrc 
            nginx-debug -g 'daemon off;'
        resources: {}
status: {}
